services:
  database:



    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: karteladb
    ports:
      - 3316:3306  # dışarıya açılan port

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin_adminPanel
    depends_on:
      - database
    environment:
      PMA_HOST: database  # database servisiyle bağlantı
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 8013:80  # dışarıya açılan port

  adminer:
    image: adminer
    restart: always
    ports:
      - 8010:8080  # dışarıya açılan port

  mailer:
    image: schickling/mailcatcher
    ports:
      - 1013:8025  # dışarıya açılan port
      - 1018:1025  # dışarıya açılan port
